# Site
repository: boseul-cho/boseul-cho.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Boseul Cho
title: MICU RN
email: boseul.cho@snu.ac.kr
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links

additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
  
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  For the past nine years, I have been working at a medical intensive care unit as a registered nurse in Asan Medical Center. 
  I am a master student in Nursing Informatics at Seoul National University.  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Project participatation 
        link: 
        link_text: http://www.kosmi.org/
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Subject : Ontology-based standardization and user tool development for utilization of person generated health data in daily life.
        description: | # this will include new lines to allow paragraphs
          
  - title: Experience
      - layout: list
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Symposium Speech
        link: The Korean Society of Medical Informatics(KOSMI) presented in 2021 fall conference
        link_text: http://www.kosmi.org/
        additional_links:
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
          - title:  Github page for project (eg. sproogen/modern-resume-theme)
            icon: fab fa-github
            url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
        quote: >
          Subject : The Role of Consumer Health Informatics for Patient-Centered Health Care
        description: | # this will include new lines to allow paragraphs
          Consumer Health Informatics Research Trend Analysis through keywords of domestic and international articles : Text mining method.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Asan Medical Center
        sub_title: Medical Intensive Care Unit
        caption: Sep 2014 - present 
        link: https://www.amc.seoul.kr/asan/main.do
        quote: >
          Registered Nurse specialized in ICU
        description: | # this will include new lines to allow paragraphs
          - Experience monitoring patient progress and with providing updates to doctors, patients, and family members.
          - Knowledge of nursing care methods, procedures, and emergency care.
          - Care for patients requiring ECMO, ventilator, CRRT, lung translantation (critical treatment, etc.).
          - Expert knowledge of health and safety guidelines/procedures (sanitation, decontamination, etc.)
  - title: Education
    layout: list
    content:
      - layout: left
        title: Seoul National University
        sub_title: MA in Nursing Informatics
        caption: 2021 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          
      - layout: left
        title: Inha University 
        sub_title: BA in Department of Nursing 
        caption: 2010 - 2014
        quote: >
          
        description: | # this will include new lines to allow paragraphs
       
  - title: Research Interests
    layout: list
    content:
      - layout: left
        title: Nursing workflow
        sub_title: 
        caption: 
        quote: >
          Clinical decision support system
        description: | # this will include new lines to allow paragraphs
        
      - layout: left
        title: Data Anaylsis 
        sub_title: 
        caption: 
        quote: >
          Ontology, Standardized terminology, Data accuracy, Quality Improvement
        description: | # this will include new lines to allow paragraphs
          
      - layout: left
        title: Artificial Intelligence
        sub_title: Machine Learning
        caption: 
        quote: >
          Text mining, Natural Language Process
        description: | # this will include new lines to allow paragraphs
        
      - layout: left
        title: Consumer Health Informatics
        sub_title: 
        caption: 
        quote: >
          Person Generated Health Data, Patient Portal, self-tracking
        description: | # this will include new lines to allow paragraphs
        
  - title: Publication
    layout: list
    content:
      - layout: left
        title: 
        sub_title: 
        caption: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
        

          
          
    

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
